FROM node:16-alpine

ARG NEXT_PUBLIC_CONTACT_FORM_GUID=${NEXT_PUBLIC_CONTACT_FORM_GUID}
ENV NEXT_PUBLIC_CONTACT_FORM_GUID=${NEXT_PUBLIC_CONTACT_FORM_GUID}

ARG NEXT_PUBLIC_PORTAL_ID=${NEXT_PUBLIC_PORTAL_ID}
ENV NEXT_PUBLIC_PORTAL_ID=${NEXT_PUBLIC_PORTAL_ID}

ARG NEXT_PUBLIC_SANITY_DATASET=${NEXT_PUBLIC_SANITY_DATASET}
ENV NEXT_PUBLIC_SANITY_DATASET=${NEXT_PUBLIC_SANITY_DATASET}

ARG NEXT_PUBLIC_SANITY_PROJECT_ID=${NEXT_PUBLIC_SANITY_PROJECT_ID}
ENV NEXT_PUBLIC_SANITY_PROJECT_ID=${NEXT_PUBLIC_SANITY_PROJECT_ID}

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY ./package*.json /usr/src/app/
RUN npm install && npm cache clean --force
COPY ./ /usr/src/app
EXPOSE ${NEXT_SERVER_PORT}
RUN [ "npm", "run", "build" ]
CMD [ "npm", "start" ]
