import Head from 'next/head'

import {  
  MainLayout, 
  TargetSection,
  CountryPresenceSection,
  BigMapSection,
  RegionsSection,
  LinksSection,
} from 'components'

export default function Home() {
  return (
    <div className="countries">
      <Head>
        <title>Global Plastic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <TargetSection />
        <CountryPresenceSection />
        <BigMapSection />
        <RegionsSection />
        <LinksSection />
      </MainLayout>
    </div>
  )
}
